# -*- coding: utf-8 -*-
"""DeeplabV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zF6DlCaeYQ71bTOlQo8PJobfY6y9MZDg
"""

from google.colab import drive
drive.mount('/content/drive')

"""Lát cắt mới"""

!pip install pynrrd matplotlib

!pip install SimpleITK

import os
import SimpleITK as sitk

file_path = "/content/drive/MyDrive/validation/oncologist/TCGA-CV-5978/CT_IMAGE.nrrd"

# Đọc ảnh
image = sitk.ReadImage(file_path)
array = sitk.GetArrayFromImage(image)

# Đếm số lượng slice
num_slices = array.shape[0]
print("Số lượng slice trong CT:", num_slices)

import matplotlib.pyplot as plt

folder_output = "/content/drive/MyDrive/Tep_moi/oncologist/TCGA-CV-5978"
os.makedirs(folder_output, exist_ok=True)

start_slice = 1
end_slice = min(144, num_slices)

print(f"Lưu slices từ {start_slice} đến {end_slice}")

for idx in range(start_slice, end_slice + 1):
    slice_img = array[idx]

    plt.figure(figsize=(6,6))
    plt.imshow(slice_img, cmap='gray')
    plt.title(f"Slice {idx}")
    plt.axis('off')

    save_path = os.path.join(folder_output, f"slice_{idx}.png")
    plt.savefig(save_path, bbox_inches='tight', pad_inches=0)
    plt.close()

print("Đã lưu xong toàn bộ hình ảnh tại:", folder_output)

import nrrd
import numpy as np
import cv2
import os

# --- CẤU HÌNH ĐƯỜNG DẪN ---
SEGMENTATION_FOLDER = '/content/drive/MyDrive/validation/oncologist/TCGA-CV-5978/segmentations'
OUTPUT_ROOT = '/content/drive/MyDrive/anh_mask/oncologist/TCGA-CV-5978'

def convert_nrrd_to_mask(nrrd_path, output_dir):
    try:
        print(f"   Đang đọc file: {nrrd_path}")
        data, header = nrrd.read(nrrd_path)

        # Tạo thư mục đầu ra nếu chưa có
        os.makedirs(output_dir, exist_ok=True)

        num_slices = data.shape[2]

        for i in range(num_slices):
            mask_slice = data[:, :, i]

            # Xử lý xoay/lật ảnh (giữ nguyên theo code cũ của bạn)
            mask_slice = np.rot90(mask_slice, k=1)
            mask_slice = np.flipud(mask_slice)

            mask_png = (mask_slice * 255).astype(np.uint8)

            save_name = f"slice_{i}.png"
            save_path = os.path.join(output_dir, save_name)

            cv2.imwrite(save_path, mask_png)

        print(f"   --> Đã xong! Lưu tại: {output_dir}")

    except Exception as e:
        print(f"   LỖI khi xử lý file {nrrd_path}: {str(e)}")

# --- CHƯƠNG TRÌNH CHÍNH: QUÉT TỰ ĐỘNG ---

if os.path.exists(SEGMENTATION_FOLDER):
    # Lấy danh sách tất cả các file trong thư mục
    all_files = os.listdir(SEGMENTATION_FOLDER)

    # Sắp xếp tên file để chạy theo thứ tự (tùy chọn)
    all_files.sort()

    print(f"Tìm thấy {len(all_files)} file trong thư mục. Bắt đầu xử lý...\n")

    for filename in all_files:
        # Chỉ xử lý những file có đuôi là .nrrd
        if filename.endswith('.nrrd'):

            # Tạo đường dẫn đầy đủ đến file nrrd
            full_nrrd_path = os.path.join(SEGMENTATION_FOLDER, filename)

            # Tạo tên thư mục đầu ra dựa trên tên file (bỏ đuôi .nrrd)
            # Ví dụ: Brain.nrrd -> masks_Brain
            organ_name = filename.replace('.nrrd', '')
            output_dir = os.path.join(OUTPUT_ROOT, f"masks_{organ_name}")

            print(f"[*] Đang xử lý: {filename}")
            convert_nrrd_to_mask(full_nrrd_path, output_dir)
            print("-" * 50)

else:
    print(f"Không tìm thấy thư mục nguồn: {SEGMENTATION_FOLDER}")

"""Chuẩn hóa Data

"""

import os
import glob
import cv2
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

DATA_FOLDER_PATH = '/content/drive/MyDrive/Tep_moi'

IMG_SIZE = (256, 256)

class CT_PNG_Dataset(Dataset):
    def __init__(self, root_dir, is_train=True):
        """
        Args:
            root_dir (string): Đường dẫn tới folder GỐC (ví dụ: Tep_moi)
            is_train (bool): True để bật chế độ tăng cường dữ liệu (xoay/lật)
        """
        self.root_dir = root_dir

        path_lower = os.path.join(root_dir, "**", "*.png")
        path_upper = os.path.join(root_dir, "**", "*.PNG")

        self.image_paths = glob.glob(path_lower, recursive=True) + \
                           glob.glob(path_upper, recursive=True)

        if len(self.image_paths) == 0:
            print(f"CẢNH BÁO: Không tìm thấy ảnh nào trong {root_dir} và các thư mục con!")
        else:
            print(f"Đã tìm thấy tổng cộng: {len(self.image_paths)} ảnh.")
            print(f"   -> Ví dụ ảnh đầu tiên: {self.image_paths[0]}")

        self.is_train = is_train
        self.transform_aug = transforms.Compose([
            transforms.ToPILImage(),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.RandomRotation(degrees=10),
            transforms.ToTensor()
        ])

        self.transform_base = transforms.Compose([
            transforms.ToTensor()
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        if image is None:
          return torch.zeros(1, 256, 256)
        image = cv2.resize(image, (256, 256))
        if self.is_train:
            image_tensor = self.transform_aug(image)
        else:
            image_tensor = self.transform_base(image)

        return image_tensor

try:
    train_dataset = CT_PNG_Dataset(root_dir=DATA_FOLDER_PATH, is_train=True)
    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)

    data_iter = iter(train_loader)
    images = next(data_iter)

    print(f"Số lượng ảnh tìm thấy: {len(train_dataset)}")
    print(f"Shape của Batch đầu vào mô hình: {images.shape}")
    print(f"Giá trị pixel max: {images.max()}, min: {images.min()}")

    plt.figure(figsize=(10, 5))
    for i in range(4):
        if i >= len(images): break
        ax = plt.subplot(1, 4, i + 1)
        img_show = images[i].squeeze().numpy()
        plt.imshow(img_show, cmap='gray')
        plt.title(f"Ảnh {i+1}")
        plt.axis('off')
    plt.show()

except Exception as e:
    print("Có lỗi xảy ra (khả năng do đường dẫn folder chưa đúng hoặc folder rỗng):")
    print(e)

import os
import cv2
import torch
import torchvision.transforms as transforms
from PIL import Image

# --- 1. CẤU HÌNH ---
# Folder chứa CT gốc
INPUT_CT_ROOT = '/content/drive/MyDrive/Tep_moi/oncologist/0522c0014'

OUTPUT_MRI_ROOT = '/content/drive/MyDrive/MRI_save'

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- 2. LOAD MÔ HÌNH ĐÃ TRAIN ---

generator = UNetGenerator().to(DEVICE)
generator.load_state_dict(torch.load("/content/drive/MyDrive/generator_ct2mri_final.pth", map_location=DEVICE))
generator.eval()
print("Đã load mô hình thành công!")

def process_single_image(img_path, save_path):
    image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if image is None: return
    transform = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize((256, 256)),
        transforms.ToTensor()
    ])
    img_tensor = transform(image).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        fake_mri = generator(img_tensor)
    fake_mri = fake_mri.cpu().squeeze().numpy()
    fake_mri = (fake_mri * 255).astype('uint8')
    cv2.imwrite(save_path, fake_mri)

# --- 3. CHẠY VÒNG LẶP QUÉT TOÀN BỘ FOLDER ---
print(f"--- BẮT ĐẦU CHUYỂN ĐỔI DỮ LIỆU ---")
print(f"Từ: {INPUT_CT_ROOT}")
print(f"Đến: {OUTPUT_MRI_ROOT}")
count = 0

for root, dirs, files in os.walk(INPUT_CT_ROOT):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            full_input_path = os.path.join(root, file)
            relative_path = os.path.relpath(full_input_path, INPUT_CT_ROOT)
            full_output_path = os.path.join(OUTPUT_MRI_ROOT, relative_path)
            os.makedirs(os.path.dirname(full_output_path), exist_ok=True)
            process_single_image(full_input_path, full_output_path)

            count += 1
            if count % 100 == 0:
                print(f"Đã xử lý: {count} ảnh...")

print(f"HOÀN TẤT! Đã tạo ra {count} ảnh MRI giả lập.")
print(f"Kiểm tra tại folder: {OUTPUT_MRI_ROOT}")

"""Xây dựng kiến trúc GAN"""

import os
import glob
import numpy as np
import cv2
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from torch.autograd import Variable

class MedicalImageDataset(Dataset):
    def __init__(self, root_dir, is_train=True):
        self.root_dir = root_dir
        self.is_train = is_train

        extensions = ["*.png", "*.PNG", "*.jpg", "*.jpeg", "*.JPG"]

        self.image_paths = []
        for ext in extensions:

            path_pattern = os.path.join(root_dir, "**", ext)
            files = glob.glob(path_pattern, recursive=True)
            self.image_paths.extend(files)

        if len(self.image_paths) == 0:
            print(f"CẢNH BÁO: Không tìm thấy ảnh nào trong: {root_dir}")
        else:
            print(f"Đã tìm thấy {len(self.image_paths)} ảnh tại: {root_dir}")

        self.transform_aug = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((256, 256)),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.ToTensor()
        ])

        self.transform_base = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((256, 256)),
            transforms.ToTensor()
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        if image is None:
            return torch.zeros(1, 256, 256)

        if self.is_train:
            return self.transform_aug(image)
        else:
            return self.transform_base(image)

class UNetGenerator(nn.Module):
    def __init__(self):
        super(UNetGenerator, self).__init__()

        def down_block(in_feat, out_feat, normalize=True):
            layers = [nn.Conv2d(in_feat, out_feat, 4, 2, 1, bias=False)]
            if normalize: layers.append(nn.BatchNorm2d(out_feat))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return nn.Sequential(*layers)

        def up_block(in_feat, out_feat, dropout=0.0):
            layers = [
                nn.ConvTranspose2d(in_feat, out_feat, 4, 2, 1, bias=False),
                nn.BatchNorm2d(out_feat),
                nn.ReLU(inplace=True)
            ]
            if dropout: layers.append(nn.Dropout(dropout))
            return nn.Sequential(*layers)

        self.down1 = down_block(1, 64, normalize=False)
        self.down2 = down_block(64, 128)
        self.down3 = down_block(128, 256)
        self.down4 = down_block(256, 512)
        self.down5 = down_block(512, 512)
        self.down6 = down_block(512, 512)

        self.up1 = up_block(512, 512, dropout=0.5)
        self.up2 = up_block(1024, 512, dropout=0.5)
        self.up3 = up_block(1024, 256)
        self.up4 = up_block(512, 128)
        self.up5 = up_block(256, 64)

        self.final = nn.Sequential(
            nn.ConvTranspose2d(128, 1, 4, 2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        d1 = self.down1(x)
        d2 = self.down2(d1)
        d3 = self.down3(d2)
        d4 = self.down4(d3)
        d5 = self.down5(d4)
        d6 = self.down6(d5)

        u1 = self.up1(d6)
        u2 = self.up2(torch.cat([u1, d5], 1))
        u3 = self.up3(torch.cat([u2, d4], 1))
        u4 = self.up4(torch.cat([u3, d3], 1))
        u5 = self.up5(torch.cat([u4, d2], 1))

        return self.final(torch.cat([u5, d1], 1))

# --- 3. MÔ HÌNH DISCRIMINATOR (PATCHGAN) ---
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()

        def discriminator_block(in_filters, out_filters, normalize=True):
            layers = [nn.Conv2d(in_filters, out_filters, 4, 2, 1)]
            if normalize: layers.append(nn.InstanceNorm2d(out_filters))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers

        self.model = nn.Sequential(
            *discriminator_block(1, 64, normalize=False),
            *discriminator_block(64, 128),
            *discriminator_block(128, 256),
            *discriminator_block(256, 512),
            nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(512, 1, 4, padding=1, bias=False)
        )

    def forward(self, img):
        return self.model(img)

import os
import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

# --- 1. CẤU HÌNH ĐƯỜNG DẪN ---
DIR_CT = '/content/drive/MyDrive/Tep_moi/oncologist/0522c0014'
DIR_MRI = '/content/drive/MyDrive/MRI_save/oncologist/0522c0014'
DIR_MASK = '/content/drive/MyDrive/Tep_moiss/oncologist/0522c0014/masks_Brainstem'

# --- 2. HÀM TÍNH CHỈ SỐ (Chỉ Accuracy) ---
def calculate_accuracy(pred, target, threshold=0.5):

    pred_bin = (pred > threshold).float()
    pred_flat = pred_bin.view(-1)
    target_flat = target.view(-1)

    tp = (pred_flat * target_flat).sum()
    fp = (pred_flat * (1 - target_flat)).sum()
    fn = ((1 - pred_flat) * target_flat).sum()
    tn = ((1 - pred_flat) * (1 - target_flat)).sum()

    accuracy = (tp + tn) / (tp + tn + fp + fn + 1e-8)

    return accuracy.item()

# --- 3. DATASET ---
class FusionDataset(Dataset):
    def __init__(self, ct_dir, mri_dir, mask_dir):
        self.ct_dir = ct_dir
        self.mri_dir = mri_dir
        self.mask_dir = mask_dir

        if os.path.exists(mask_dir):
            self.filenames = [f for f in os.listdir(mask_dir) if f.endswith('.png')]
            print(f" Tìm thấy {len(self.filenames)} mẫu dữ liệu.")
        else:
            self.filenames = []
            print(f" Lỗi: Không tìm thấy folder mask tại {mask_dir}")

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        fname = self.filenames[idx]

        ct_path = os.path.join(self.ct_dir, fname)
        mri_path = os.path.join(self.mri_dir, fname)
        mask_path = os.path.join(self.mask_dir, fname)

        ct = cv2.imread(ct_path, cv2.IMREAD_GRAYSCALE)
        mri = cv2.imread(mri_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if ct is None: ct = np.zeros((256, 256), dtype=np.uint8)
        if mri is None: mri = np.zeros((256, 256), dtype=np.uint8)

        ct = cv2.resize(ct, (256, 256))
        mri = cv2.resize(mri, (256, 256))
        mask = cv2.resize(mask, (256, 256))

        mask = (mask > 127).astype(np.float32)

        to_tensor = transforms.ToTensor()
        return to_tensor(ct), to_tensor(mri), torch.from_numpy(mask).unsqueeze(0)

# --- 4. MODEL ---
class LateFusionModel(nn.Module):
    def __init__(self):
        super(LateFusionModel, self).__init__()
        # Encoder CT
        self.enc_ct = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(),
            nn.Conv2d(32, 32, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        # Encoder MRI
        self.enc_mri = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(),
            nn.Conv2d(32, 32, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        # Fusion
        self.fusion_conv = nn.Conv2d(64, 64, 3, padding=1)
        # Decoder
        self.decoder = nn.Sequential(
            nn.Conv2d(64, 64, 3, padding=1), nn.ReLU(),
            nn.Upsample(scale_factor=2),
            nn.Conv2d(64, 32, 3, padding=1), nn.ReLU(),
            nn.Conv2d(32, 1, 1),
            nn.Sigmoid()
        )

    def forward(self, ct, mri):
        f1 = self.enc_ct(ct)
        f2 = self.enc_mri(mri)
        f_cat = torch.cat([f1, f2], dim=1)
        f_fused = self.fusion_conv(f_cat)
        return self.decoder(f_fused)

# --- 5. TRAINING LOOP ---
dataset = FusionDataset(DIR_CT, DIR_MRI, DIR_MASK)

if len(dataset) > 0:
    dataloader = DataLoader(dataset, batch_size=8, shuffle=True)
    model = LateFusionModel().to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.BCELoss()

    print("\n BẮT ĐẦU TRAINING...")
    NUM_EPOCHS = 100

    for epoch in range(NUM_EPOCHS):
        model.train()
        epoch_loss = 0
        epoch_acc = 0

        for ct, mri, mask in dataloader:
            ct, mri, mask = ct.to(DEVICE), mri.to(DEVICE), mask.to(DEVICE)

            optimizer.zero_grad()
            prediction = model(ct, mri)
            loss = criterion(prediction, mask)
            loss.backward()
            optimizer.step()

            # Chỉ tính Accuracy
            acc = calculate_accuracy(prediction, mask)

            epoch_loss += loss.item()
            epoch_acc += acc

        # In kết quả
        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] | "
              f"Loss: {epoch_loss/len(dataloader):.4f} | "
              f"Acc: {epoch_acc/len(dataloader):.4f}")

    # Lưu model
    torch.save(model.state_dict(), "late_fusion_segmentation.pth")
    print("\n Đã lưu mô hình: late_fusion_segmentation.pth")
else:
    print(" Lỗi: Không tìm thấy dữ liệu!")

#Baseline Model (Chỉ dùng CT)
import os
import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

DIR_CT = '/content/drive/MyDrive/Tep_moi/oncologist/0522c0014'
DIR_MASK = '/content/drive/MyDrive/Tep_moiss/oncologist/0522c0014/masks_Brainstem'

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class DiceLoss(nn.Module):
    def __init__(self, smooth=1):
        super(DiceLoss, self).__init__()
        self.smooth = smooth
    def forward(self, inputs, targets):
        inputs = inputs.view(-1)
        targets = targets.view(-1)
        intersection = (inputs * targets).sum()
        dice = (2. * intersection + self.smooth) / (inputs.sum() + targets.sum() + self.smooth)
        return 1 - dice

model = BaselineUNet().to(DEVICE)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

criterion = DiceLoss()

print("\nBẮT ĐẦU TRAINING BASELINE (DICE LOSS)...")

for epoch in range(20):
    model.train()
    epoch_loss = 0
    for ct, mask in train_loader:
        ct, mask = ct.to(DEVICE), mask.to(DEVICE)

        optimizer.zero_grad()
        pred = model(ct)

        loss = criterion(pred, mask)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    print(f"Epoch {epoch+1}/20 | Loss: {epoch_loss/len(train_loader):.4f}")

print("\nĐANG CHẠY TEST LẠI...")
model.eval()
dice_scores = []

with torch.no_grad():
    for ct, mask in test_loader:
        ct, mask = ct.to(DEVICE), mask.to(DEVICE)
        pred = model(ct)

        if mask.max() > 0:
            pred_bin = (pred > 0.5).float()
            intersection = (pred_bin * mask).sum()
            dice = (2. * intersection) / (pred_bin.sum() + mask.sum() + 1e-8)
            dice_scores.append(dice.item())

if len(dice_scores) > 0:
    avg_dice = sum(dice_scores) / len(dice_scores)
    print("="*40)
    print(f"KẾT QUẢ BASELINE MỚI (DICE LOSS):")
    print(f"Average Dice Score: {avg_dice:.4f}")
    print("="*40)

# --- DATASET ĐÃ LỌC (Chỉ lấy ảnh có cơ quan) ---
class SingleChannelDataset(Dataset):
    def __init__(self, ct_dir, mask_dir):
        self.ct_dir = ct_dir
        self.mask_dir = mask_dir
        self.filenames = []

        # Bước lọc dữ liệu (Hơi lâu một chút lúc khởi tạo)
        print("⏳ Đang lọc dữ liệu (Chỉ lấy lát cắt CÓ cơ quan)...")
        if os.path.exists(mask_dir):
            all_files = [f for f in os.listdir(mask_dir) if f.endswith('.png')]

            for f in all_files:
                mask_path = os.path.join(mask_dir, f)
                # Đọc nhanh mask để kiểm tra
                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                if mask is not None and np.max(mask) > 0: # Chỉ lấy nếu có vệt trắng
                    self.filenames.append(f)

        print(f"Đã lọc xong! Còn lại {len(self.filenames)} mẫu chất lượng (trên tổng số {len(all_files) if os.path.exists(mask_dir) else 0}).")

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        fname = self.filenames[idx]
        ct_path = os.path.join(self.ct_dir, fname)
        mask_path = os.path.join(self.mask_dir, fname)

        ct = cv2.imread(ct_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if ct is None: ct = np.zeros((256, 256), dtype=np.uint8)

        ct = cv2.resize(ct, (256, 256))
        mask = cv2.resize(mask, (256, 256))

        mask = (mask > 127).astype(np.float32)

        to_tensor = transforms.ToTensor()
        return to_tensor(ct), torch.from_numpy(mask).unsqueeze(0)

class BaselineUNet(nn.Module):
    def __init__(self):
        super(BaselineUNet, self).__init__()

        self.enc1 = nn.Sequential(nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(), nn.Conv2d(32, 32, 3, padding=1), nn.ReLU())
        self.pool1 = nn.MaxPool2d(2)

        self.enc2 = nn.Sequential(nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.Conv2d(64, 64, 3, padding=1), nn.ReLU())
        self.pool2 = nn.MaxPool2d(2)

        self.bottleneck = nn.Sequential(nn.Conv2d(64, 128, 3, padding=1), nn.ReLU(), nn.Conv2d(128, 128, 3, padding=1), nn.ReLU())

        self.up2 = nn.Upsample(scale_factor=2)
        self.dec2 = nn.Sequential(nn.Conv2d(128 + 64, 64, 3, padding=1), nn.ReLU(), nn.Conv2d(64, 64, 3, padding=1), nn.ReLU())

        self.up1 = nn.Upsample(scale_factor=2)
        self.dec1 = nn.Sequential(nn.Conv2d(64 + 32, 32, 3, padding=1), nn.ReLU(), nn.Conv2d(32, 32, 3, padding=1), nn.ReLU())

        self.final = nn.Sequential(nn.Conv2d(32, 1, 1), nn.Sigmoid())

    def forward(self, x):

        e1 = self.enc1(x)
        p1 = self.pool1(e1)

        e2 = self.enc2(p1)
        p2 = self.pool2(e2)

        b = self.bottleneck(p2)

        d2 = self.up2(b)
        d2 = torch.cat((d2, e2), dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        d1 = torch.cat((d1, e1), dim=1)
        d1 = self.dec1(d1)

        return self.final(d1)

# --- 4. HÀM TÍNH METRICS ---
def calculate_metrics(pred, target, threshold=0.5):
    pred_bin = (pred > threshold).float()
    intersection = (pred_bin * target).sum()
    dice = (2. * intersection) / (pred_bin.sum() + target.sum() + 1e-8)
    return dice.item()

# --- 5. CHẠY THỰC NGHIỆM ---
full_dataset = SingleChannelDataset(DIR_CT, DIR_MASK)

if len(full_dataset) > 0:
    # 1. Chia tập Train/Test (80% train, 20% test)
    train_size = int(0.8 * len(full_dataset))
    test_size = len(full_dataset) - train_size
    train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])

    train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False) # Batch 1 để test từng ảnh

    print(f"Tổng dữ liệu: {len(full_dataset)}")
    print(f"Train set: {len(train_dataset)} | Test set: {len(test_dataset)}")

    # 2. Huấn luyện
    model = BaselineUNet().to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.BCELoss()

    print("\nBẮT ĐẦU TRAINING BASELINE (CHỈ CT)...")
    for epoch in range(20): # Train nhanh 20 epoch để so sánh
        model.train()
        epoch_loss = 0
        for ct, mask in train_loader:
            ct, mask = ct.to(DEVICE), mask.to(DEVICE)
            optimizer.zero_grad()
            pred = model(ct)
            loss = criterion(pred, mask)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        print(f"Epoch {epoch+1}/20 | Loss: {epoch_loss/len(train_loader):.4f}")

    # 3. Đánh giá trên tập Test (QUAN TRỌNG)
    print("\n📊 ĐANG CHẠY TRÊN TẬP TEST...")
    model.eval()
    dice_scores = []

    with torch.no_grad():
        for ct, mask in test_loader:
            ct, mask = ct.to(DEVICE), mask.to(DEVICE)
            pred = model(ct)

            # Chỉ tính Dice nếu mask có cơ quan (để tránh nhiễu do ảnh đen)
            if mask.max() > 0:
                dice = calculate_metrics(pred, mask)
                dice_scores.append(dice)

    if len(dice_scores) > 0:
        avg_dice = sum(dice_scores) / len(dice_scores)
        print("="*40)
        print(f"KẾT QUẢ BASELINE (CT ONLY):")
        print(f"Average Dice Score: {avg_dice:.4f}")
        print("="*40)
    else:
        print("Tập test toàn ảnh đen, không tính được Dice chính xác.")

else:
    print("Không tìm thấy dữ liệu!")

# --- 5. HIỂN THỊ KẾT QUẢ (CHỌN LỌC) ---
model.eval()
found_mask = False
print("Đang tìm lát cắt có cơ quan để hiển thị...")

with torch.no_grad():
    for ct, mri, mask in dataloader:
        if mask.max() > 0:

            ct, mri = ct.to(DEVICE), mri.to(DEVICE)
            pred = model(ct, mri)

            for i in range(ct.size(0)):
                if mask[i].max() > 0:
                    img_ct = ct[i].cpu().squeeze()
                    img_mri = mri[i].cpu().squeeze()
                    img_mask = mask[i].cpu().squeeze()
                    img_pred = pred[i].cpu().squeeze()

                    plt.figure(figsize=(16, 5))

                    plt.subplot(1, 4, 1)
                    plt.imshow(img_ct, cmap='gray')
                    plt.title("Input CT (Kênh 1)")
                    plt.axis('off')

                    plt.subplot(1, 4, 2)
                    plt.imshow(img_mri, cmap='gray')
                    plt.title("Synthetic MRI (Kênh 2)")
                    plt.axis('off')

                    plt.subplot(1, 4, 3)
                    plt.imshow(img_mask, cmap='gray')
                    plt.title("True Mask (Đáp án)")
                    plt.axis('off')

                    plt.subplot(1, 4, 4)
                    plt.imshow(img_pred > 0.5, cmap='gray')
                    plt.title("AI Predicted (Kết quả)")
                    plt.axis('off')

                    plt.show()

                    found_mask = True
                    break

        if found_mask:
            break

if not found_mask:
    print("Không tìm thấy ảnh nào có Mask trong lượt random này. Hãy chạy lại cell này lần nữa!")

"""code mới"""

import os
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import glob
import random
from PIL import Image

# --- CẤU HÌNH ---
IMG_SIZE = 256
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_PATH = '/content/drive/MyDrive/unet_best.pth'

# 👇 DÁN ĐƯỜNG DẪN THƯ MỤC ẢNH CỦA BẠN VÀO GIỮA 2 DẤU NHÁY DƯỚI ĐÂY 👇
TEST_DIR = '/content/drive/MyDrive/anh_ct/oncologist/0522c0014'
# (Ví dụ: /content/anh_ct/oncologist/0522c0014 - Bạn nhớ thay cho đúng nhé)

# --- KIẾN TRÚC MODEL (GIỮ NGUYÊN BẢN PHỤC CHẾ ĐÃ CHẠY ĐƯỢC) ---
class ConvBlock(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_c, out_c, 3, padding=1),
            nn.BatchNorm2d(out_c),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_c, out_c, 3, padding=1),
            nn.BatchNorm2d(out_c),
            nn.ReLU(inplace=True)
        )
    def forward(self, x):
        return self.conv(x)

class RestoredUNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.d1 = ConvBlock(1, 64)
        self.d2 = ConvBlock(64, 128)
        self.d3 = ConvBlock(128, 256)
        self.bot = ConvBlock(256, 512)
        self.pool = nn.MaxPool2d(2, 2)

        self.up1 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.u1 = ConvBlock(512, 256)

        self.up2 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.u2 = ConvBlock(256, 128)

        self.up3 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.u3 = ConvBlock(128, 64)

        self.final = nn.Conv2d(64, 1, kernel_size=1)

    def forward(self, x):
        d1 = self.d1(x)
        p1 = self.pool(d1)
        d2 = self.d2(p1)
        p2 = self.pool(d2)
        d3 = self.d3(p2)
        p3 = self.pool(d3)
        bot = self.bot(p3)

        x = self.up1(bot)
        if x.shape != d3.shape: x = F.interpolate(x, size=d3.shape[2:])
        x = torch.cat([d3, x], dim=1)
        x = self.u1(x)

        x = self.up2(x)
        if x.shape != d2.shape: x = F.interpolate(x, size=d2.shape[2:])
        x = torch.cat([d2, x], dim=1)
        x = self.u2(x)

        x = self.up3(x)
        if x.shape != d1.shape: x = F.interpolate(x, size=d1.shape[2:])
        x = torch.cat([d1, x], dim=1)
        x = self.u3(x)

        return self.final(x)

# --- CHẠY TEST TỰ ĐỘNG TỪ THƯ MỤC ---
def run_test_folder():
    # 1. Load Model
    print(f"🔄 Đang nạp model cũ từ {MODEL_PATH}...")
    try:
        model = RestoredUNet().to(DEVICE)
        model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
        model.eval()
        print("✅ Nạp model thành công!")
    except Exception as e:
        print(f"❌ Lỗi model: {str(e)}")
        return

    # 2. Quét ảnh trong thư mục
    print(f"📂 Đang tìm ảnh trong: {TEST_DIR}")
    files = glob.glob(os.path.join(TEST_DIR, '*.png')) + glob.glob(os.path.join(TEST_DIR, '*.jpg'))

    if len(files) == 0:
        print("❌ Không tìm thấy file ảnh nào (.png, .jpg) trong thư mục này!")
        print("👉 Bạn hãy kiểm tra lại đường dẫn xem đúng chưa nhé.")
        return

    # 3. Chọn ngẫu nhiên 1 ảnh để test
    test_file = random.choice(files)
    print(f"✨ Đã chọn ngẫu nhiên ảnh: {os.path.basename(test_file)}")

    # 4. Xử lý và Dự đoán
    img_origin = cv2.imread(test_file, 0)
    if img_origin is None:
        print("❌ Lỗi đọc file ảnh (file có thể bị hỏng).")
        return

    img_resized = cv2.resize(img_origin, (IMG_SIZE, IMG_SIZE))
    img_tensor = torch.tensor(img_resized/255.0, dtype=torch.float32).unsqueeze(0).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        pred = model(img_tensor)
        pred = torch.sigmoid(pred)
        pred_mask = (pred > 0.5).float().cpu().numpy()[0, 0]

    # 5. Vẽ kết quả
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 3, 1)
    plt.title("Ảnh CT Gốc")
    plt.imshow(img_resized, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.title("AI Dự đoán (Mask)")
    plt.imshow(pred_mask, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.title("Kết quả chồng lớp")
    plt.imshow(img_resized, cmap='gray')
    plt.imshow(pred_mask, cmap='jet', alpha=0.5)
    plt.axis('off')

    plt.show()

if __name__ == "__main__":
    run_test_folder()

import matplotlib.pyplot as plt
import pandas as pd

# Đọc file log của bạn
# Đảm bảo file log_train1.txt nằm cùng thư mục với file code này
df = pd.read_csv('/content/drive/MyDrive/log_train1.txt')

# Cấu hình biểu đồ
plt.figure(figsize=(12, 5))

# --- BIỂU ĐỒ 1: LOSS ---
plt.subplot(1, 2, 1)
plt.plot(df['Epoch'], df['Train_Loss'], label='Train Loss', color='blue', linewidth=2)
plt.plot(df['Epoch'], df['Val_Loss'], label='Val Loss', color='red', linestyle='--', linewidth=2)
plt.title('Quá trình giảm hàm mất mát (Loss)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True, alpha=0.3)

# --- BIỂU ĐỒ 2: DICE & ACCURACY ---
plt.subplot(1, 2, 2)
plt.plot(df['Epoch'], df['Val_Dice'], label='Dice Score', color='green', linewidth=2)
# Accuracy cao quá nên ta vẽ trục phụ hoặc chỉ vẽ Dice để nhìn cho rõ dao động
plt.plot(df['Epoch'], df['Val_Acc'], label='Accuracy', color='orange', linestyle='--', linewidth=2)
plt.title('Hiệu năng mô hình (Dice & Accuracy)')
plt.xlabel('Epoch')
plt.ylabel('Score')
plt.legend()
plt.grid(True, alpha=0.3)

# Lưu ảnh
plt.tight_layout()
plt.savefig('ket_qua_train.png', dpi=300)
print("Đã vẽ xong biểu đồ! Mở file 'ket_qua_train.png' để xem.")
plt.show()

import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
import glob
import re
import random

# --- CẤU HÌNH ---
IMG_SIZE = 256
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

MODEL_PATH = '/content/drive/MyDrive/unet_best_dice.pth'
CT_DIR = '/content/drive/MyDrive/anh_ct'
MRI_DIR = '/content/drive/MyDrive/MRI_save'
MASK_DIR = '/content/drive/MyDrive/anh_mask'

# --- 1. MODEL DEFINITION ---
class TwoChannelUNet(nn.Module):
    def __init__(self):
        super().__init__()
        def CBR(in_c, out_c):
            return nn.Sequential(
                nn.Conv2d(in_c, out_c, 3, padding=1),
                nn.BatchNorm2d(out_c),
                nn.ReLU(inplace=True),
                nn.Conv2d(out_c, out_c, 3, padding=1),
                nn.BatchNorm2d(out_c),
                nn.ReLU(inplace=True)
            )
        self.enc1 = CBR(2, 64)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = CBR(64, 128)
        self.pool2 = nn.MaxPool2d(2)
        self.enc3 = CBR(128, 256)
        self.pool3 = nn.MaxPool2d(2)
        self.bottle = CBR(256, 512)
        self.up3 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.dec3 = CBR(512, 256)
        self.up2 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.dec2 = CBR(256, 128)
        self.up1 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.dec1 = CBR(128, 64)
        self.final = nn.Conv2d(64, 1, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))
        b = self.bottle(self.pool3(e3))
        d3 = self.dec3(torch.cat((self.up3(b), e3), dim=1))
        d2 = self.dec2(torch.cat((self.up2(d3), e2), dim=1))
        d1 = self.dec1(torch.cat((self.up1(d2), e1), dim=1))
        return self.final(d1)

# --- 2. HÀM QUÉT FILE THÔNG MINH (SMART SCAN) ---
def get_random_pair():
    print("🔄 Đang quét dữ liệu (Smart Scan)...")

    def extract_id(filename):
        numbers = re.findall(r'\d+', filename)
        return int(numbers[-1]) if numbers else None

    # Hàm tìm file đệ quy (quét sâu vào thư mục con)
    def index_files(root_dir):
        file_map = {}
        # Tìm tất cả các đuôi ảnh phổ biến
        extensions = ['*.png', '*.jpg', '*.jpeg', '*.tif', '*.bmp']
        files = []
        for ext in extensions:
            # recursive=True giúp tìm cả trong thư mục con
            files.extend(glob.glob(os.path.join(root_dir, '**', ext), recursive=True))

        for f in files:
            fid = extract_id(os.path.basename(f))
            if fid is not None:
                file_map[fid] = f
        return file_map, len(files)

    # Quét từng thư mục
    ct_map, n_ct = index_files(CT_DIR)
    mri_map, n_mri = index_files(MRI_DIR)
    mask_map, n_mask = index_files(MASK_DIR)

    print(f"   -> Tìm thấy: {n_ct} CT, {n_mri} MRI, {n_mask} Mask")

    # Tìm ID chung
    common_ids = list(set(ct_map.keys()) & set(mri_map.keys()) & set(mask_map.keys()))

    if not common_ids:
        print("❌ VẪN KHÔNG TÌM THẤY! Hãy kiểm tra lại đường dẫn thư mục CT_DIR, MRI_DIR.")
        print(f"   Đường dẫn hiện tại đang set là: {CT_DIR}")
        return None, None, None

    # Bốc ngẫu nhiên 1 ID
    random_id = random.choice(common_ids)
    print(f"✨ Đã chọn ngẫu nhiên ID: {random_id}")
    return ct_map[random_id], mri_map[random_id], mask_map[random_id]

# --- 3. DỰ ĐOÁN & VẼ ẢNH ---
def predict_and_show():
    # 1. Lấy ảnh
    ct_path, mri_path, mask_path = get_random_pair()
    if ct_path is None: return

    print(f"   - CT: {ct_path}")
    print(f"   - MRI: {mri_path}")

    # 2. Load Model
    if not os.path.exists(MODEL_PATH):
        print(f"❌ Không tìm thấy file model: {MODEL_PATH}")
        print("   -> Bạn nhớ sửa biến MODEL_PATH ở đầu file cho đúng tên file model nhé!")
        return

    model = TwoChannelUNet().to(DEVICE)
    try:
        model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
    except Exception as e:
        print(f"❌ Lỗi khi load model: {e}")
        return

    model.eval()

    # 3. Xử lý ảnh đầu vào
    ct_img = cv2.imread(ct_path, 0)
    mri_img = cv2.imread(mri_path, 0)

    ct_resized = cv2.resize(ct_img, (IMG_SIZE, IMG_SIZE)) / 255.0
    mri_resized = cv2.resize(mri_img, (IMG_SIZE, IMG_SIZE)) / 255.0

    ct_tensor = torch.tensor(ct_resized, dtype=torch.float32).unsqueeze(0)
    mri_tensor = torch.tensor(mri_resized, dtype=torch.float32).unsqueeze(0)
    input_tensor = torch.cat([ct_tensor, mri_tensor], dim=0).unsqueeze(0).to(DEVICE)

    # 4. Dự đoán
    with torch.no_grad():
        output = model(input_tensor)
        pred_mask = torch.sigmoid(output).cpu().numpy()[0, 0]
        pred_binary = (pred_mask > 0.5).astype(np.float32)

    # 5. Load Mask thật
    gt_mask = cv2.imread(mask_path, 0)
    gt_mask = cv2.resize(gt_mask, (IMG_SIZE, IMG_SIZE)) / 255.0

    # 6. Vẽ và Lưu
    plt.figure(figsize=(15, 5))

    plt.subplot(1, 4, 1); plt.imshow(ct_resized, cmap='gray'); plt.title("CT Input"); plt.axis('off')
    plt.subplot(1, 4, 2); plt.imshow(mri_resized, cmap='gray'); plt.title("MRI Input"); plt.axis('off')
    plt.subplot(1, 4, 3); plt.imshow(gt_mask, cmap='gray'); plt.title("Ground Truth"); plt.axis('off')
    plt.subplot(1, 4, 4); plt.imshow(pred_binary, cmap='gray'); plt.title("Prediction"); plt.axis('off')

    save_name = f"result_id_{os.path.basename(ct_path)}"
    plt.savefig(save_name)
    print(f"✅ XONG! Kết quả đã lưu vào file: {save_name}")

if __name__ == "__main__":
    predict_and_show()

"""Ảnh MRI

"""

import os
import cv2
import numpy as np
from tqdm import tqdm  # Thư viện tạo thanh tiến trình cho đẹp

# ==========================================
# 1. CẤU HÌNH ĐƯỜNG DẪN
# ==========================================
# Thư mục gốc chứa ảnh CT (Nguồn)
INPUT_ROOT = '/content/drive/MyDrive/anh_ct'

# Thư mục gốc để lưu ảnh MRI giả lập (Đích)
OUTPUT_ROOT = '/content/drive/MyDrive/MRI_save'

# Các đuôi file ảnh chấp nhận
VALID_EXTS = ('.png', '.jpg', '.jpeg', '.bmp')

# ==========================================
# 2. HÀM XỬ LÝ CHÍNH
# ==========================================
def create_mri_dataset():
    count = 0
    print(f"🚀 Bắt đầu quét và chuyển đổi ảnh từ: {INPUT_ROOT}")
    print(f"📂 Ảnh kết quả sẽ lưu tại: {OUTPUT_ROOT}\n")

    # Duyệt qua tất cả các thư mục con
    for root, dirs, files in os.walk(INPUT_ROOT):
        for file in files:
            if file.lower().endswith(VALID_EXTS):
                # --- A. XÁC ĐỊNH ĐƯỜNG DẪN ---
                # Đường dẫn file gốc
                src_path = os.path.join(root, file)

                # Tính toán đường dẫn đích (giữ nguyên cấu trúc thư mục)
                # Ví dụ: root = .../anh_ct/patient1 -> rel_path = patient1
                rel_path = os.path.relpath(root, INPUT_ROOT)

                # Đường dẫn thư mục đích tương ứng
                dest_dir = os.path.join(OUTPUT_ROOT, rel_path)

                # Nếu thư mục đích chưa có thì tạo mới
                if not os.path.exists(dest_dir):
                    os.makedirs(dest_dir)

                # Đường dẫn file đích
                dest_path = os.path.join(dest_dir, file)

                # --- B. XỬ LÝ ẢNH (THUẬT TOÁN) ---
                try:
                    # 1. Đọc ảnh CT (Grayscale)
                    ct_img = cv2.imread(src_path, 0)

                    if ct_img is None:
                        continue # Bỏ qua nếu lỗi đọc file

                    # 2. Tạo MRI giả lập (Invert + Blur)
                    # Công thức: MRI = 255 - CT
                    mri_fake = 255 - ct_img

                    # Làm mờ nhẹ (Gaussian Blur)
                    mri_fake = cv2.GaussianBlur(mri_fake, (3,3), 0)

                    # 3. Lưu ảnh
                    cv2.imwrite(dest_path, mri_fake)
                    count += 1

                    # In ra tiến trình (mỗi 100 ảnh báo 1 lần cho đỡ rối)
                    if count % 100 == 0:
                        print(f"✅ Đã xử lý {count} ảnh... (Đang ở: {rel_path})")

                except Exception as e:
                    print(f"❌ Lỗi file {file}: {e}")

    print("\n" + "="*40)
    print(f"🎉 HOÀN TẤT! TỔNG CỘNG ĐÃ TẠO: {count} ẢNH MRI GIẢ LẬP.")
    print(f"👉 Bạn hãy vào folder '{OUTPUT_ROOT}' để kiểm tra nhé.")
    print("="*40)

# ==========================================
# 3. CHẠY CHƯƠNG TRÌNH
# ==========================================
if __name__ == "__main__":
    if os.path.exists(INPUT_ROOT):
        create_mri_dataset()
    else:
        print(f"❌ Lỗi: Không tìm thấy thư mục nguồn: {INPUT_ROOT}")
        print("Bạn kiểm tra lại đường dẫn Google Drive xem đúng chưa nhé.")